apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot-1.9-test-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/mvaldron-rhdh/chatbot-1.9-test-1:4af705c60c2b65ce983c2b394f66cf60b3f0f799@sha256:979c2fbc320e1d33d18a4ba18996453e8e44ab279467ca08a86b578065f10010 # use pre-built to bootstrap
          name: app-inference
